run-type: client
local-addr: 127.0.0.1
local-port: 1082

remote-addr: y.ueky.cn

remote-port: 443
password:
  - "uekycn3738"

# ---------------------------------------------------------
# TLS 深度伪装与安全
# ---------------------------------------------------------
ssl:
  enabled: true
  verify: false 
  # 开启 Session Reuse 减少握手延迟
  reuse_session: true
  session_ticket: true

mux:
  # 架构建议：WS 模式下 Mux 建议开启。
  # 若发现大文件下载速度受限，可尝试关闭观察。
  enabled: false
  concurrency: 8
  idle_timeout: 60

tcp:
  no_delay: true
  keep_alive: true
  prefer_ipv4: true

# ---------------------------------------------------------
# 智能路由与分流 (重点优化)
# ---------------------------------------------------------
router:
  enabled: true
  # 策略优化：as_is 减少 DNS 查询开销，防止本地 DNS 污染影响判断
  domain_strategy: as_is 
  
  # 规则优先级：Block > Bypass > Proxy
  block:
    - 'geosite:category-ads-all' # 增强广告过滤
  
  bypass:
    - 'geoip:cn'
    - 'geoip:private'
    - 'geosite:cn'
    - 'geosite:private'
    - 'domain:baidu.com' 
  
  proxy:
    - 'geosite:geolocation-!cn'

  default_policy: proxy
  geoip: ./geoip.dat
  geosite: ./geosite.dat
